on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current package version
        id: current_version
        run: echo "::set-output name=version::$(make version)"
      - name: Publish to NPM
        run: |
          npm version ${{ steps.current_version.outputs.version }}
          npm publish
