on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.current_version.outputs.version }}
    steps:
      - name: Get current package version
        id: current_version
        run: echo "::set-output name=version::$(make version)"

  release:
    needs: prepare
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ needs.prepare.outputs.version }}"
          prerelease: false
          files: |
            ./bin/supdock-macos
            ./bin/supdock-aarch64-linux
            ./bin/supdock-amd64-linux

  publish:
    needs: prepare
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Cargo
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
      - name: Publish to NPM
        run: |
          npm version ${{ needs.prepare.outputs.version }}
          npm publish --dry-run
