on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
      - uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: ${{ needs.build.outputs.version }}
          draft: false
          prerelease: false
      - name: Upload Assets to Release with a wildcard
        uses: csexton/release-asset-action@v2
        with:
          pattern: "bin/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Cargo
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
      - name: Get current package version
        id: current_version
        run: echo "::set-output name=version::$(make version)"
      - name: Publish to NPM
        run: |
          npm version ${{ steps.current_version.outputs.version }}
          npm publish --dry-run
